/**
 * Database Templates - SQL Migration Generation
 */

export function sqlMigration(
  appName: string,
  entities: Array<{ name: string; fields: Array<{ name: string; type: string; nullable?: boolean }> }>
): string {
  const tables = entities.map(e => {
    const cols = e.fields
      .filter(f => f.name !== 'id' && f.name !== 'createdAt' && f.name !== 'updatedAt')
      .map(f => `  ${snake(f.name)} ${sqlType(f.type)}${f.nullable ? '' : ' NOT NULL'}`)
      .join(',\n');

    return `CREATE TABLE IF NOT EXISTS ${snake(e.name)}s (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
${cols},
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`;
  }).join('\n\n');

  return `-- ${appName} Database Migration
-- Generated by Reclapp

${tables}
`;
}

function snake(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
}

function sqlType(t: string): string {
  const map: Record<string, string> = {
    String: 'TEXT',
    Int: 'INTEGER',
    Float: 'DOUBLE PRECISION',
    Decimal: 'DECIMAL(10,2)',
    Boolean: 'BOOLEAN',
    DateTime: 'TIMESTAMPTZ',
    Date: 'DATE',
    UUID: 'UUID',
    JSON: 'JSONB',
    Money: 'DECIMAL(12,2)',
    Email: 'VARCHAR(255)',
    URL: 'TEXT'
  };
  return map[t] || 'TEXT';
}

export { snake, sqlType };
