/**
 * Entity Types
 * Auto-generated TypeScript types from Pydantic contracts
 * DO NOT EDIT - Generated by pycontracts.generate
 */

/** CRM Contact entity */
export interface Contact {
  /** Unique identifier */
  id: string;
  /** Contact email address */
  email: string;
  firstName: string;
  lastName: string;
  phone?: string | null;
  companyId?: string | null;
  position?: string | null;
  notes?: string | null;
  createdAt?: string;
  updatedAt?: string | null;
}

/** CRM Company entity */
export interface Company {
  /** Unique identifier */
  id: string;
  name: string;
  domain?: string | null;
  website?: string | null;
  industry?: string | null;
  size?: string | null;
  revenue?: number | null;
  address?: string | null;
  city?: string | null;
  country?: string | null;
  createdAt?: string;
  updatedAt?: string | null;
}

/** CRM Deal/Opportunity entity */
export interface Deal {
  /** Unique identifier */
  id: string;
  title: string;
  value: number;
  currency?: string;
  stage?: "lead" | "qualified" | "proposal" | "negotiation" | "won" | "lost";
  probability?: number;
  contactId?: string | null;
  companyId?: string | null;
  expectedClose?: string | null;
  notes?: string | null;
  createdAt?: string;
  updatedAt?: string | null;
  closedAt?: string | null;
}

/** System User entity */
export interface User {
  /** Unique identifier */
  id: string;
  /** User email */
  email: string;
  name: string;
  role?: "admin" | "user" | "viewer";
  avatarUrl?: string | null;
  isActive?: boolean;
  lastLogin?: string | null;
  createdAt?: string;
}

/** Task/Todo entity */
export interface Task {
  /** Unique identifier */
  id: string;
  title: string;
  description?: string | null;
  status?: "todo" | "in_progress" | "done" | "cancelled";
  priority?: "low" | "medium" | "high" | "urgent";
  assigneeId?: string | null;
  projectId?: string | null;
  dueDate?: string | null;
  completedAt?: string | null;
  createdAt?: string;
  updatedAt?: string | null;
}

/** Project entity */
export interface Project {
  /** Unique identifier */
  id: string;
  name: string;
  description?: string | null;
  status?: "planning" | "active" | "on_hold" | "completed" | "cancelled";
  ownerId?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  budget?: number | null;
  createdAt?: string;
  updatedAt?: string | null;
}
