/**
 * LLM Output Types
 * Auto-generated TypeScript types from Contract AI models
 * DO NOT EDIT - Generated by scripts/generate_schemas.py
 */

/** A single generated file */
export interface GeneratedFile {
  path: string;
  content: string;
  target?: "api" | "frontend" | "shared" | "docker";
  language?: string | null;
}

/** Complete LLM code generation output */
export interface LLMCodeOutput {
  files: GeneratedFile[];
  model?: string;
  tokensUsed?: number;
  generationTimeMs?: number;
}

/** Complete pipeline validation result */
export interface PipelineResult {
  passed: boolean;
  stages: StageResult[];
  summary: PipelineSummary;
}

/** Complete validation result with feedback */
export interface ValidationResult {
  pipeline: PipelineResult;
  feedback?: CorrectionFeedback | null;
  success?: boolean;
  iterationsUsed?: number;
}
