/**
 * Markdown Contract Writer (.rcl.md)
 * Converts IR (Intermediate Representation) to .rcl.md format
 */

import { IR, Entity, EnumDef, EventDef, AlertDef, PipelineDef, DashboardDef, SourceDef, WorkflowDef, Message } from '../parser/markdown';

export interface WriteOptions {
  includeConversation?: boolean;
  includeTimestamp?: boolean;
  language?: 'pl' | 'en';
  prettyTitles?: boolean;
}

const LABELS = {
  pl: {
    properties: 'Właściwość',
    value: 'Wartość',
    version: 'Wersja',
    author: 'Autor',
    license: 'Licencja',
    created: 'Utworzono',
    conversation: 'Rozmowa',
    entities: 'Encje',
    enums: 'Typy wyliczeniowe',
    events: 'Zdarzenia',
    alerts: 'Alerty',
    pipelines: 'Przepływy danych',
    dashboards: 'Panele',
    sources: 'Źródła danych',
    workflows: 'Przepływy pracy',
    api: 'Konfiguracja API',
    deployment: 'Deployment',
    env: 'Zmienne środowiskowe',
    generatedBy: 'Wygenerowano przez Reclapp Studio',
  },
  en: {
    properties: 'Property',
    value: 'Value',
    version: 'Version',
    author: 'Author',
    license: 'License',
    created: 'Created',
    conversation: 'Conversation',
    entities: 'Entities',
    enums: 'Enums',
    events: 'Events',
    alerts: 'Alerts',
    pipelines: 'Pipelines',
    dashboards: 'Dashboards',
    sources: 'Data Sources',
    workflows: 'Workflows',
    api: 'API Configuration',
    deployment: 'Deployment',
    env: 'Environment Variables',
    generatedBy: 'Generated by Reclapp Studio',
  },
};

export function writeMarkdownContract(
  ir: IR,
  conversation: Message[] = [],
  options: WriteOptions = {}
): string {
  const { includeConversation = true, includeTimestamp = true, language = 'pl', prettyTitles = false } = options;
  const L = LABELS[language];
  const lines: string[] = [];

  // Header
  lines.push(`# ${ir.app.name}`);
  lines.push('');

  if (ir.app.description) {
    lines.push(`> ${ir.app.description}`);
    lines.push('');
  }

  // Metadata table
  lines.push(`| ${L.properties} | ${L.value} |`);
  lines.push('|------------|---------|');
  lines.push(`| ${L.version} | ${ir.app.version || '1.0.0'} |`);
  if (ir.app.author) {
    lines.push(`| ${L.author} | ${ir.app.author} |`);
  }
  if (ir.app.license) {
    lines.push(`| ${L.license} | ${ir.app.license} |`);
  }
  if (includeTimestamp) {
    lines.push(`| ${L.created} | ${new Date().toISOString().split('T')[0]} |`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // Conversation
  if (includeConversation && conversation.length > 0) {
    lines.push(`## 💬 ${L.conversation}`);
    lines.push('');

    for (const msg of conversation) {
      const emoji = msg.role === 'user' ? '🧑' : '🤖';
      const role = msg.role === 'user' ? 'User' : 'Assistant';
      lines.push(`### ${emoji} ${role} (${msg.timestamp})`);
      lines.push('');
      lines.push(msg.content);
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Entities
  if (ir.entities.length > 0) {
    lines.push(`## 📦 ${L.entities}`);
    lines.push('');

    for (const entity of ir.entities) {
      lines.push(`### ${entity.name}`);
      lines.push('');
      lines.push('```yaml');
      lines.push(`# entity: ${entity.name}`);

      for (const field of entity.fields) {
        const modifiers: string[] = [];
        if (field.unique) modifiers.push('@unique');
        if (field.explicitRequired) modifiers.push('@required');
        if (field.auto) modifiers.push('@auto');

        const modStr = modifiers.join(' ');
        const commentParts: string[] = [];
        if (modStr) commentParts.push(modStr);
        if (field.defaultValue) commentParts.push(`= ${field.defaultValue}`);
        if (field.description) commentParts.push(`- ${field.description}`);
        const comment = commentParts.length > 0 ? `# ${commentParts.join(' ')}` : '';

        const typeStr = field.type + (field.nullable && !field.type.endsWith('?') ? '?' : '');
        const line = `${field.name.padEnd(16)}: ${typeStr.padEnd(21)}${comment}`;
        lines.push(line.trimEnd());
      }

      lines.push('```');
      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }

  // Enums
  if (ir.enums.length > 0) {
    lines.push(`## 🏷️ ${L.enums}`);
    lines.push('');

    for (const enumDef of ir.enums) {
      lines.push('```yaml');
      lines.push(`# enum: ${enumDef.name}`);

      for (const value of enumDef.values) {
        const desc = value.description ? ` # ${value.description}` : '';
        lines.push(`- ${value.name.padEnd(14)}${desc}`.trimEnd());
      }

      lines.push('```');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Events
  if (ir.events.length > 0) {
    lines.push(`## 📡 ${L.events}`);
    lines.push('');

    for (const event of ir.events) {
      lines.push(`### ${event.name}`);
      lines.push('');
      lines.push('```yaml');
      lines.push(`# event: ${event.name}`);

      for (const field of event.fields) {
        lines.push(`${field.name.padEnd(16)}: ${field.type}`);
      }

      lines.push('```');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Alerts
  if (ir.alerts.length > 0) {
    lines.push(`## 🚨 ${L.alerts}`);
    lines.push('');

    for (const alert of ir.alerts) {
      lines.push(`### ${prettyTitles ? humanizeTitle(alert.name) : alert.name}`);
      lines.push('');
      lines.push('```yaml');
      lines.push(`# alert: ${alert.name}`);
      if (alert.entity) {
        lines.push(`entity: ${alert.entity}`);
      }
      lines.push(`when: ${alert.condition}`);
      lines.push(`notify: [${(alert.targets || []).join(', ')}]`);
      lines.push(`severity: ${alert.severity}`);
      if (alert.message) {
        lines.push(`message: "${alert.message}"`);
      }
      lines.push('```');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Pipelines
  if (ir.pipelines.length > 0) {
    lines.push(`## 🔄 ${L.pipelines}`);
    lines.push('');

    for (const pipeline of ir.pipelines) {
      lines.push(`### ${pipeline.name}`);
      lines.push('');
      lines.push('```yaml');
      lines.push(`# pipeline: ${pipeline.name}`);
      lines.push(`input: [${(pipeline.input || []).join(', ')}]`);
      lines.push(`output: ${pipeline.output}`);
      if (pipeline.schedule) {
        lines.push(`schedule: "${pipeline.schedule}"`);
      }
      if (pipeline.transform && pipeline.transform.length > 0) {
        lines.push(`transform: [${pipeline.transform.join(', ')}]`);
      }
      lines.push('```');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Sources
  if (ir.sources.length > 0) {
    lines.push(`## 🔌 ${L.sources}`);
    lines.push('');

    for (const source of ir.sources) {
      lines.push(`### ${prettyTitles ? humanizeTitle(source.name) : source.name}`);
      lines.push('');
      lines.push('```yaml');
      lines.push(`# source: ${source.name}`);
      lines.push(`type: ${source.type}`);
      if (source.url) {
        lines.push(`url: "${source.url}"`);
      }
      if (source.auth) {
        lines.push(`auth: ${source.auth}`);
      }
      if (source.cache) {
        lines.push(`cache: "${source.cache}"`);
      }
      lines.push('```');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Workflows
  if (ir.workflows.length > 0) {
    lines.push(`## ⚙️ ${L.workflows}`);
    lines.push('');

    for (const workflow of ir.workflows) {
      lines.push(`### ${prettyTitles ? humanizeTitle(workflow.name) : workflow.name}`);
      lines.push('');
      lines.push('```yaml');
      lines.push(`# workflow: ${workflow.name}`);
      lines.push(`trigger: ${workflow.trigger}`);
      lines.push(`steps: [${workflow.steps.join(', ')}]`);
      lines.push('```');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Dashboards
  if (ir.dashboards.length > 0) {
    lines.push(`## 📊 ${L.dashboards}`);
    lines.push('');

    for (const dashboard of ir.dashboards) {
      lines.push(`### ${prettyTitles ? humanizeTitle(dashboard.name) : dashboard.name}`);
      lines.push('');
      lines.push('```yaml');
      lines.push(`# dashboard: ${dashboard.name}`);
      if (dashboard.entity) {
        lines.push(`entity: ${dashboard.entity}`);
      }
      lines.push(`metrics: [${(dashboard.metrics || []).join(', ')}]`);
      if (dashboard.stream) {
        lines.push(`stream: ${dashboard.stream}`);
      }
      if (dashboard.layout) {
        lines.push(`layout: ${dashboard.layout}`);
      }
      lines.push('```');
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  if (ir.api) {
    lines.push(`## 🌐 ${L.api}`);
    lines.push('');
    lines.push('```yaml');
    lines.push('# api:');
    lines.push(`prefix: ${ir.api.prefix || '/api'}`);
    if (ir.api.auth) {
      lines.push(`auth: ${ir.api.auth}`);
    }
    if (ir.api.rateLimit) {
      lines.push(`rateLimit: ${ir.api.rateLimit}`);
    }
    if (ir.api.cors) {
      lines.push(`cors: ${ir.api.cors}`);
    }
    lines.push('```');
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Deployment
  if (ir.deployment) {
    lines.push(`## 🚀 ${L.deployment}`);
    lines.push('');
    lines.push('```yaml');
    lines.push('# deployment:');
    lines.push(`type: ${ir.deployment.type}`);
    lines.push(`database: ${ir.deployment.database}`);
    if (ir.deployment.cache) {
      lines.push(`cache: ${ir.deployment.cache}`);
    }
    lines.push('```');
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Environment variables
  if (ir.env.length > 0) {
    lines.push(`## 🔐 ${L.env}`);
    lines.push('');
    lines.push('```yaml');
    lines.push('# env:');

    for (const envVar of ir.env) {
      const modifiers: string[] = [];
      if (envVar.required) modifiers.push('@required');

      const modStr = modifiers.join(' ');
      const defaultStr = envVar.default ? `= "${envVar.default}"` : '';
      
      const commentParts: string[] = [];
      if (modStr) commentParts.push(modStr);
      if (defaultStr) commentParts.push(defaultStr);
      const comment = commentParts.length > 0 ? `# ${commentParts.join(' ')}` : '';

      lines.push(`${envVar.name.padEnd(16)}: ${envVar.type.padEnd(21)}${comment}`.trimEnd());
    }

    lines.push('```');
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Footer
  if (ir.aiPlan) {
    lines.push('---');
    lines.push('');
    lines.push('## 🤖 Plan AI');
    lines.push('');
    lines.push('```json:contract.ai.json');
    lines.push(JSON.stringify(ir.aiPlan, null, 2));
    lines.push('```');
    lines.push('');
  }

  lines.push(`*${L.generatedBy}*`);
  lines.push('');

  return lines.join('\n');
}

// Convert contract format to IR for writing
export function contractToIR(contract: any): IR {
  return {
    app: {
      name: contract.app?.name || contract.name || 'Unnamed',
      version: contract.app?.version || contract.version || '1.0.0',
      description: contract.app?.description || contract.description,
      author: contract.app?.author,
      license: contract.app?.license,
    },
    entities: (contract.entities || []).map((e: any) => ({
      name: e.name,
      fields: (e.fields || []).map((f: any) => ({
        name: f.name,
        type: f.rclType || mapTypeToRcl(f.type, f.name),
        required: f.required,
        explicitRequired: !!f.explicitRequired,
        unique: f.unique,
        auto: f.auto,
        nullable: typeof f.rclType === 'string' ? f.rclType.trim().endsWith('?') : false,
        defaultValue: f.default,
        description: f.description,
      })),
    })),
    enums: contract.enums || [],
    events: contract.events || [],
    alerts: contract.alerts || [],
    pipelines: contract.pipelines || [],
    dashboards: contract.dashboards || [],
    sources: contract.sources || [],
    workflows: contract.workflows || [],
    api: contract.api,
    deployment: contract.deployment,
    env: contract.env || [],
    config: contract.config || {},
    aiPlan: contract.aiPlan || contract.generation || contract.definition || contract.frontmatter ? contract : undefined,
  };
}

function mapTypeToRcl(type: string, fieldName?: string): string {
  if (!type) return 'text';
  if (type.startsWith('->')) return type;

  const typeMap: Record<string, string> = {
    String: 'text',
    Int: 'int',
    Float: 'float',
    Boolean: 'bool',
    Date: 'date',
    DateTime: 'datetime',
    Json: 'json',
  };

  const mapped = typeMap[type] || type.toLowerCase();
  const n = (fieldName || '').toLowerCase();

  // If it's a known system type but capitalized, normalize it
  if (typeMap[type]) return mapped;

  if (mapped === 'text') {
    const businessIdRegex = /tax|vat|national|citizen|business|regon|krs|nip|pesel/i;
    if ((n === 'id' || n.endsWith('id')) && !businessIdRegex.test(n)) return 'uuid';
    if (n.includes('email')) return 'email';
    if (n.includes('phone')) return 'phone';
    if (n === 'url' || n.endsWith('url')) return 'url';
  }
  
  // Custom types (Entities, Enums) are capitalized
  if (type.length > 0 && type[0] === type[0].toUpperCase()) {
    // Check if it's not a primitive type that just happened to be capitalized
    const primitives = ['String', 'Number', 'Boolean', 'Date', 'DateTime', 'Json', 'Array', 'Object'];
    if (!primitives.includes(type)) {
      return type;
    }
  }

  return mapped;
}

function humanizeTitle(name: string): string {
  // Special cases for acronyms
  const specialCases: Record<string, string> = {
    'VIESVAT': 'VIES VAT',
    'KRSRegistry': 'KRS Registry',
    'CEIDGRegistry': 'CEIDG Registry',
  };
  
  if (specialCases[name]) return specialCases[name];

  return name
    .replace(/_/g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1 $2')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/\s+/g, ' ')
    .trim();
}
