#!/usr/bin/env npx ts-node
/**
 * Reclapp Generator CLI
 * 
 * Usage:
 *   npx ts-node scripts/generate.ts <contract-path> [output-dir]
 * 
 * Examples:
 *   npx ts-node scripts/generate.ts examples/crm/contracts/main.reclapp.ts
 *   npx ts-node scripts/generate.ts examples/crm/contracts/main.reclapp.ts examples/crm/target
 */

import * as path from 'path';
import * as fs from 'fs';

// Types imported inline to avoid tsconfig issues
interface ReclappContract {
  app: { name: string; version: string; description: string; author?: string; license?: string };
  deployment?: any;
  backend?: any;
  frontend?: any;
  entities?: any[];
  events?: any[];
  pipelines?: any[];
  alerts?: any[];
  dashboards?: any[];
  workflows?: any[];
  api?: any;
  env?: any[];
  docker?: any;
  config?: Record<string, any>;
  sources?: any[];
  websocket?: any;
  ipc?: any;
  tray?: any;
  scheduler?: any;
}

// ============================================================================
// SIMPLE GENERATOR (Inline to avoid import issues)
// ============================================================================

interface GeneratedFile {
  path: string;
  content: string;
}

class SimpleGenerator {
  private contract: ReclappContract;
  private output: string;
  private files: GeneratedFile[] = [];

  constructor(contract: ReclappContract, output: string) {
    this.contract = contract;
    this.output = output;
  }

  generate(): GeneratedFile[] {
    console.log(`\nGenerating ${this.contract.app.name} v${this.contract.app.version}...`);
    console.log(`Output: ${this.output}\n`);

    this.generateApi();
    this.generateFrontend();
    this.generateDatabase();
    this.generateDocker();
    this.generateProjectFiles();

    return this.files;
  }

  private addFile(relativePath: string, content: string): void {
    this.files.push({
      path: path.join(this.output, relativePath),
      content
    });
  }

  private generateApi(): void {
    const entities = this.contract.entities || [];

    // Server
    this.addFile('api/src/server.ts', this.serverTemplate(entities));

    // Routes
    for (const entity of entities) {
      this.addFile(
        `api/src/routes/${this.kebab(entity.name)}.ts`,
        this.routeTemplate(entity)
      );
    }

    // Models
    for (const entity of entities) {
      this.addFile(
        `api/src/models/${this.kebab(entity.name)}.ts`,
        this.modelTemplate(entity)
      );
    }

    // Package.json
    this.addFile('api/package.json', JSON.stringify({
      name: `${this.kebab(this.contract.app.name)}-api`,
      version: this.contract.app.version,
      scripts: {
        dev: "ts-node-dev --respawn src/server.ts",
        build: "tsc",
        start: "node dist/server.js"
      },
      dependencies: {
        express: "^4.18.2",
        cors: "^2.8.5",
        helmet: "^7.1.0"
      },
      devDependencies: {
        "@types/express": "^4.17.21",
        "@types/cors": "^2.8.17",
        "@types/node": "^20.10.0",
        typescript: "^5.3.2",
        "ts-node-dev": "^2.0.0"
      }
    }, null, 2));

    // tsconfig
    this.addFile('api/tsconfig.json', JSON.stringify({
      compilerOptions: {
        target: "ES2022",
        module: "commonjs",
        outDir: "./dist",
        rootDir: "./src",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true
      },
      include: ["src/**/*"]
    }, null, 2));
  }

  private serverTemplate(entities: any[]): string {
    const imports = entities.map(e => 
      `import ${this.camel(e.name)}Routes from './routes/${this.kebab(e.name)}';`
    ).join('\n');

    const routes = entities.map(e =>
      `app.use('/api/${this.kebab(e.name)}s', ${this.camel(e.name)}Routes);`
    ).join('\n  ');

    return `/**
 * ${this.contract.app.name} - API Server
 * Generated by Reclapp
 */

import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import helmet from 'helmet';

${imports}

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());

app.get('/api/health', (req, res) => {
  res.json({ status: 'healthy', name: '${this.contract.app.name}', version: '${this.contract.app.version}' });
});

${routes}

app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
  console.error(err);
  res.status(500).json({ error: 'Internal server error' });
});

const PORT = process.env.PORT || 8080;
app.listen(PORT, () => console.log(\`Server running on port \${PORT}\`));

export default app;
`;
  }

  private routeTemplate(entity: any): string {
    const name = entity.name;
    const lower = this.camel(name);

    return `/**
 * ${name} Routes - Generated by Reclapp
 */

import { Router, Request, Response } from 'express';

const router = Router();
let ${lower}s: any[] = [];
let nextId = 1;

router.get('/', (req, res) => {
  res.json({ data: ${lower}s, total: ${lower}s.length });
});

router.get('/:id', (req, res) => {
  const item = ${lower}s.find(i => i.id === req.params.id);
  if (!item) return res.status(404).json({ error: 'Not found' });
  res.json({ data: item });
});

router.post('/', (req, res) => {
  const item = { id: String(nextId++), ...req.body, createdAt: new Date().toISOString() };
  ${lower}s.push(item);
  res.status(201).json({ data: item });
});

router.put('/:id', (req, res) => {
  const idx = ${lower}s.findIndex(i => i.id === req.params.id);
  if (idx === -1) return res.status(404).json({ error: 'Not found' });
  ${lower}s[idx] = { ...${lower}s[idx], ...req.body, updatedAt: new Date().toISOString() };
  res.json({ data: ${lower}s[idx] });
});

router.delete('/:id', (req, res) => {
  const idx = ${lower}s.findIndex(i => i.id === req.params.id);
  if (idx === -1) return res.status(404).json({ error: 'Not found' });
  ${lower}s.splice(idx, 1);
  res.status(204).send();
});

export default router;
`;
  }

  private modelTemplate(entity: any): string {
    const fields = (entity.fields || []).map((f: any) => 
      `  ${f.name}${f.nullable ? '?' : ''}: ${this.tsType(f.type)};`
    ).join('\n');

    return `/**
 * ${entity.name} Model - Generated by Reclapp
 */

export interface ${entity.name} {
  id: string;
${fields}
  createdAt: string;
  updatedAt?: string;
}
`;
  }

  private generateFrontend(): void {
    const entities = this.contract.entities || [];

    // App.tsx
    this.addFile('frontend/src/App.tsx', this.appTemplate(entities));
    this.addFile('frontend/src/main.tsx', `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode><App /></React.StrictMode>
);
`);

    // Components
    for (const entity of entities) {
      this.addFile(
        `frontend/src/components/${entity.name}List.tsx`,
        this.componentTemplate(entity)
      );
    }

    // Hooks
    this.addFile('frontend/src/hooks/useApi.ts', this.hooksTemplate(entities));

    // CSS
    this.addFile('frontend/src/index.css', `@tailwind base;
@tailwind components;
@tailwind utilities;
`);

    // Config files
    this.addFile('frontend/package.json', JSON.stringify({
      name: `${this.kebab(this.contract.app.name)}-frontend`,
      version: this.contract.app.version,
      type: "module",
      scripts: { dev: "vite", build: "vite build" },
      dependencies: { react: "^18.2.0", "react-dom": "^18.2.0" },
      devDependencies: {
        "@types/react": "^18.2.43",
        "@types/react-dom": "^18.2.17",
        "@vitejs/plugin-react": "^4.2.1",
        tailwindcss: "^3.3.6",
        autoprefixer: "^10.4.16",
        postcss: "^8.4.32",
        typescript: "^5.3.2",
        vite: "^5.0.8"
      }
    }, null, 2));

    this.addFile('frontend/vite.config.ts', `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
export default defineConfig({
  plugins: [react()],
  server: { port: 3000, proxy: { '/api': 'http://localhost:8080' } }
});
`);

    this.addFile('frontend/index.html', `<!DOCTYPE html>
<html><head><meta charset="UTF-8" /><title>${this.contract.app.name}</title></head>
<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>
</html>`);

    this.addFile('frontend/tailwind.config.js', `export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: { extend: {} },
  plugins: []
};`);

    this.addFile('frontend/postcss.config.js', `export default {
  plugins: { tailwindcss: {}, autoprefixer: {} }
};`);
  }

  private appTemplate(entities: any[]): string {
    const imports = entities.map(e => 
      `import ${e.name}List from './components/${e.name}List';`
    ).join('\n');

    const navItems = entities.map(e => 
      `{ id: '${this.kebab(e.name)}s', label: '${e.name}s' }`
    ).join(', ');

    const cases = entities.map(e => 
      `case '${this.kebab(e.name)}s': return <${e.name}List />;`
    ).join('\n      ');

    return `import React, { useState } from 'react';
import './index.css';
${imports}

function App() {
  const [tab, setTab] = useState('${entities[0] ? this.kebab(entities[0].name) + 's' : 'home'}');
  const navItems = [${navItems}];

  const renderContent = () => {
    switch (tab) {
      ${cases}
      default: return <div className="text-center py-8">Welcome to ${this.contract.app.name}</div>;
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex">
      <aside className="w-64 bg-white border-r p-4">
        <h1 className="text-xl font-bold mb-4">${this.contract.app.name}</h1>
        <nav className="space-y-1">
          {navItems.map(item => (
            <button key={item.id} onClick={() => setTab(item.id)}
              className={\`w-full text-left px-3 py-2 rounded \${tab === item.id ? 'bg-blue-50 text-blue-700' : 'hover:bg-gray-100'}\`}>
              {item.label}
            </button>
          ))}
        </nav>
      </aside>
      <main className="flex-1 p-8">{renderContent()}</main>
    </div>
  );
}
export default App;
`;
  }

  private componentTemplate(entity: any): string {
    const name = entity.name;
    const fields = (entity.fields || []).slice(0, 4);

    return `import React, { useEffect, useState } from 'react';

function ${name}List() {
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/${this.kebab(name)}s')
      .then(r => r.json())
      .then(d => { setItems(d.data || []); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  if (loading) return <div className="text-center py-8">Loading...</div>;

  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-bold">${name}s</h2>
      <div className="bg-white rounded-lg shadow overflow-hidden">
        <table className="min-w-full">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">ID</th>
${fields.map((f: any) => `              <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">${f.name}</th>`).join('\n')}
            </tr>
          </thead>
          <tbody className="divide-y">
            {items.map((item: any) => (
              <tr key={item.id}>
                <td className="px-4 py-3 text-sm">{item.id}</td>
${fields.map((f: any) => `                <td className="px-4 py-3 text-sm">{String(item.${f.name} ?? '-')}</td>`).join('\n')}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
export default ${name}List;
`;
  }

  private hooksTemplate(entities: any[]): string {
    return `import { useState, useEffect } from 'react';

${entities.map(e => `
export function use${e.name}s() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const refetch = async () => {
    try {
      setLoading(true);
      const res = await fetch('/api/${this.kebab(e.name)}s');
      setData(await res.json());
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { refetch(); }, []);
  return { data, loading, error, refetch };
}

export function useCreate${e.name}() {
  const [loading, setLoading] = useState(false);
  const create = async (data: any) => {
    setLoading(true);
    try {
      const res = await fetch('/api/${this.kebab(e.name)}s', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data)
      });
      return await res.json();
    } finally { setLoading(false); }
  };
  return { create, loading };
}

export function useDelete${e.name}() {
  const remove = async (id: string) => {
    await fetch(\`/api/${this.kebab(e.name)}s/\${id}\`, { method: 'DELETE' });
  };
  return { remove };
}
`).join('\n')}
`;
  }

  private generateDatabase(): void {
    const entities = this.contract.entities || [];

    const tables = entities.map(e => {
      const cols = (e.fields || []).map((f: any) => 
        `  ${this.snake(f.name)} ${this.sqlType(f.type)}${f.nullable ? '' : ' NOT NULL'}`
      ).join(',\n');

      return `CREATE TABLE IF NOT EXISTS ${this.snake(e.name)}s (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
${cols},
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);`;
    }).join('\n\n');

    this.addFile('database/migrations/001_init.sql', `-- ${this.contract.app.name} Database
-- Generated by Reclapp

${tables}
`);
  }

  private generateDocker(): void {
    this.addFile('docker/Dockerfile.api', `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 8080
CMD ["node", "dist/server.js"]
`);

    this.addFile('docker/Dockerfile.frontend', `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
`);

    this.addFile('docker-compose.yml', `version: '3.8'

services:
  api:
    build: { context: ./api, dockerfile: ../docker/Dockerfile.api }
    ports: ["8080:8080"]
    depends_on: [postgres]

  frontend:
    build: { context: ./frontend, dockerfile: ../docker/Dockerfile.frontend }
    ports: ["3000:80"]
    depends_on: [api]

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${this.snake(this.contract.app.name)}
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata:
`);
  }

  private generateProjectFiles(): void {
    this.addFile('README.md', `# ${this.contract.app.name}

${this.contract.app.description || ''}

**Version:** ${this.contract.app.version}
**Generated by:** Reclapp

## Quick Start

\`\`\`bash
# API
cd api && npm install && npm run dev

# Frontend (in another terminal)
cd frontend && npm install && npm run dev
\`\`\`

## Docker

\`\`\`bash
docker-compose up -d
\`\`\`

## API Endpoints

${(this.contract.entities || []).map(e => `- \`/api/${this.kebab(e.name)}s\` - ${e.name} CRUD`).join('\n')}
`);

    this.addFile('.env.example', `NODE_ENV=development
PORT=8080
DATABASE_URL=postgresql://app:password@localhost:5432/${this.snake(this.contract.app.name)}
`);

    this.addFile('.gitignore', `node_modules/
dist/
.env
*.log
`);
  }

  // Utilities
  private kebab(s: string): string { return s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase(); }
  private camel(s: string): string { return s.charAt(0).toLowerCase() + s.slice(1); }
  private snake(s: string): string { return s.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase(); }
  private tsType(t: string): string {
    const map: Record<string, string> = {
      String: 'string', Int: 'number', Float: 'number', Decimal: 'number',
      Boolean: 'boolean', DateTime: 'string', Date: 'string', UUID: 'string',
      JSON: 'Record<string, any>', Money: 'number', Email: 'string', URL: 'string'
    };
    return map[t] || 'any';
  }
  private sqlType(t: string): string {
    const map: Record<string, string> = {
      String: 'TEXT', Int: 'INTEGER', Float: 'DOUBLE PRECISION', Decimal: 'DECIMAL(10,2)',
      Boolean: 'BOOLEAN', DateTime: 'TIMESTAMPTZ', Date: 'DATE', UUID: 'UUID',
      JSON: 'JSONB', Money: 'DECIMAL(12,2)', Email: 'VARCHAR(255)', URL: 'TEXT'
    };
    return map[t] || 'TEXT';
  }
}

// ============================================================================
// MAIN
// ============================================================================

async function main() {
  const args = process.argv.slice(2);
  
  if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
    console.log(`
Reclapp Generator

Usage:
  npx ts-node scripts/generate.ts <contract-path> [output-dir]

Examples:
  npx ts-node scripts/generate.ts examples/crm/contracts/main.reclapp.ts
  npx ts-node scripts/generate.ts examples/crm/contracts/main.reclapp.ts examples/crm/target
`);
    process.exit(0);
  }

  const contractPath = path.resolve(args[0]);
  const outputDir = args[1] ? path.resolve(args[1]) : path.join(path.dirname(contractPath), '..', 'target');

  if (!fs.existsSync(contractPath)) {
    console.error(`Error: Contract file not found: ${contractPath}`);
    process.exit(1);
  }

  console.log(`Loading contract: ${contractPath}`);

  // Import contract
  const module = require(contractPath);
  const contract: ReclappContract = module.contract || module.default || module;

  if (!contract.app?.name) {
    console.error('Error: Invalid contract - missing app.name');
    process.exit(1);
  }

  // Generate
  const generator = new SimpleGenerator(contract, outputDir);
  const files = generator.generate();

  // Write files
  let written = 0;
  for (const file of files) {
    const dir = path.dirname(file.path);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(file.path, file.content, 'utf-8');
    console.log(`  ✓ ${path.relative(outputDir, file.path)}`);
    written++;
  }

  console.log(`\n✅ Generated ${written} files to ${outputDir}`);
  console.log(`
Next steps:
  cd ${path.relative(process.cwd(), outputDir)}/api && npm install && npm run dev
  cd ${path.relative(process.cwd(), outputDir)}/frontend && npm install && npm run dev
`);
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
