"""
Reclapp Models - Pydantic models for Contract AI

Re-exports from canonical package: reclapp-contracts (reclapp_contracts.models).
Replaces TypeScript types from src/core/contract-ai/types/
"""

from reclapp_contracts.models import (
    FieldType,
    BasicFieldType,
    ExtendedFieldType,
    RelationType,
    FieldAnnotations,
    FieldDefinition,
    RelationDefinition,
    IndexDefinition,
    EntityDefinition,
    EventDefinition,
    WorkflowStepType,
    WorkflowStepDefinition,
    WorkflowDefinition,
    ApiOperation,
    ApiResourceDefinition,
    ApiEndpointDefinition,
    ApiDefinition,
    AppDefinition,
    DefinitionLayer,
    InstructionPriority,
    Instruction,
    PatternType,
    Pattern,
    ConstraintType,
    Constraint,
    BackendTechStack,
    FrontendTechStack,
    DatabaseTechStack,
    TechStack,
    GenerationLayer,
    AssertionType,
    Assertion,
    TestType,
    TestDefinition,
    StaticRule,
    QualityGate,
    AcceptanceCriteria,
    ValidationLayer,
    ContractMetadata,
    ContractAI,
    is_valid_contract,
)

__all__ = [
    # Definition types
    "FieldType",
    "BasicFieldType", 
    "ExtendedFieldType",
    "RelationType",
    "FieldAnnotations",
    "FieldDefinition",
    "RelationDefinition",
    "IndexDefinition",
    "EntityDefinition",
    "EventDefinition",
    "WorkflowStepType",
    "WorkflowStepDefinition",
    "WorkflowDefinition",
    "ApiOperation",
    "ApiResourceDefinition",
    "ApiEndpointDefinition",
    "ApiDefinition",
    "AppDefinition",
    "DefinitionLayer",
    # Generation types
    "InstructionPriority",
    "Instruction",
    "PatternType",
    "Pattern",
    "ConstraintType",
    "Constraint",
    "BackendTechStack",
    "FrontendTechStack",
    "DatabaseTechStack",
    "TechStack",
    "GenerationLayer",
    # Validation types
    "AssertionType",
    "Assertion",
    "TestType",
    "TestDefinition",
    "StaticRule",
    "QualityGate",
    "AcceptanceCriteria",
    "ValidationLayer",
    # Contract
    "ContractMetadata",
    "ContractAI",
    "is_valid_contract",
]
