/**
 * E2E Tests Template (Native Fetch)
 * 
 * This template uses native fetch API - NO playwright, NO jest, NO mocha.
 * Variables: {{PORT}}, {{ENTITY}}, {{PLURAL}}, {{BASE_PATH}}
 */

export const e2eTestsTemplate = `/**
 * API E2E Tests - Auto-generated by Reclapp Evolution
 * @type: api_e2e_tests
 * @layer: api
 * @entity: {{ENTITY}}
 * @basePath: {{BASE_PATH}}
 */

const BASE_URL = 'http://localhost:{{PORT}}';
const API_PATH = '{{BASE_PATH}}';

interface TestResult {
  name: string;
  layer: string;
  passed: boolean;
  error?: string;
  duration_ms: number;
}

const results: TestResult[] = [];

async function e2e(layer: string, name: string, fn: () => Promise<void>): Promise<void> {
  const start = Date.now();
  try {
    await fn();
    results.push({ name, layer, passed: true, duration_ms: Date.now() - start });
    console.log(\`✅ [\${layer}] \${name}\`);
  } catch (error: any) {
    results.push({ name, layer, passed: false, error: error.message, duration_ms: Date.now() - start });
    console.log(\`❌ [\${layer}] \${name}: \${error.message}\`);
  }
}

async function runE2ETests(): Promise<void> {
  console.log('\\n## E2E Tests - API Layer\\n');

  // Health check
  await e2e('api', 'Health endpoint responds', async () => {
    const res = await fetch(\`\${BASE_URL}/health\`);
    if (!res.ok) throw new Error(\`Status: \${res.status}\`);
  });

  // CRUD E2E tests
  let createdId: string | null = null;

  await e2e('api', \`CREATE - POST \${API_PATH}\`, async () => {
    const res = await fetch(\`\${BASE_URL}\${API_PATH}\`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({{TEST_PAYLOAD}})
    });
    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(\`Status: \${res.status}\${text ? ' - ' + text.substring(0, 100) : ''}\`);
    }
    const data = await res.json();
    createdId = data.id;
    if (!createdId) throw new Error('No ID returned');
  });

  await e2e('api', \`READ - GET \${API_PATH}\`, async () => {
    const res = await fetch(\`\${BASE_URL}\${API_PATH}\`);
    if (!res.ok) throw new Error(\`Status: \${res.status}\`);
    const data = await res.json();
    if (!Array.isArray(data)) throw new Error('Expected array');
  });

  await e2e('api', \`READ - GET \${API_PATH}/:id\`, async () => {
    if (!createdId) throw new Error('No ID from create test');
    const res = await fetch(\`\${BASE_URL}\${API_PATH}/\${createdId}\`);
    if (!res.ok) throw new Error(\`Status: \${res.status}\`);
  });

  await e2e('api', \`UPDATE - PUT \${API_PATH}/:id\`, async () => {
    if (!createdId) throw new Error('No ID from create test');
    const res = await fetch(\`\${BASE_URL}\${API_PATH}/\${createdId}\`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({{UPDATE_PAYLOAD}})
    });
    if (res.status !== 200 && res.status !== 404) throw new Error(\`Status: \${res.status}\`);
  });

  await e2e('api', \`DELETE - DELETE \${API_PATH}/:id\`, async () => {
    if (!createdId) throw new Error('No ID from create test');
    const res = await fetch(\`\${BASE_URL}\${API_PATH}/\${createdId}\`, { method: 'DELETE' });
    if (!res.ok) throw new Error(\`Status: \${res.status}\`);
  });

  // Summary
  const passed = results.filter(r => r.passed).length;
  const failed = results.filter(r => !r.passed).length;
  
  console.log(\`\\n## E2E Test Results\\n\`);
  console.log(\`\\\`\\\`\\\`yaml\`);
  console.log(\`# @type: e2e_test_results\`);
  console.log(\`summary:\`);
  console.log(\`  total: \${results.length}\`);
  console.log(\`  passed: \${passed}\`);
  console.log(\`  failed: \${failed}\`);
  console.log(\`  layers_tested: ["api"]\`);
  console.log(\`tests:\`);
  for (const r of results) {
    console.log(\`  - layer: "\${r.layer}"\`);
    console.log(\`    name: "\${r.name}"\`);
    console.log(\`    passed: \${r.passed}\`);
    console.log(\`    duration_ms: \${r.duration_ms}\`);
    if (r.error) console.log(\`    error: "\${r.error}"\`);
  }
  console.log(\`\\\`\\\`\\\`\`);

  if (failed > 0) process.exit(1);
}

runE2ETests().catch(e => {
  console.error('E2E Test runner error:', e);
  process.exit(1);
});
`;

export default e2eTestsTemplate;
